#: __init__.py:97
msgid "NextGIS geoinformation system"
msgstr "Геоинформационная система NextGIS"

#: __init__.py:219
msgid "Linux kernel"
msgstr "Ядро Linux"

#: __init__.py:222
msgid "OS distribution"
msgstr "Дистрибутив ОС"

#: __init__.py:234
msgid "CPU"
msgstr "Процессор"

#: __init__.py:238
msgid "RAM"
msgstr "ОЗУ"

#: exception.py:90
msgid "Validation error"
msgstr "Ошибка валидации"

#: exception.py:95
msgid "Forbidden"
msgstr "Запрещено"

#: exception.py:100
msgid "Insufficient permissions"
msgstr "Недостаточно прав"

#: exception.py:105
msgid "Operational error"
msgstr "Операционная ошибка"

#: exception.py:110
msgid "External service error"
msgstr "Ошибка внешнего сервиса"

#: storage.py:257
msgid "Storage full"
msgstr "Хранилище переполнено"

#: storage.py:258
#, python-format
msgid ""
"This operation can't be performed because the storage limit (%s) has been "
"already exceeded by %s."
msgstr ""
"Операция не может быть выполнена, так как лимит использования хранилища (%s) "
"уже превышен на %s."

#: storage.py:266
msgid "Not enough storage"
msgstr "Недостаточно места в хранилище"

#: storage.py:267
#, python-format
msgid ""
"This operation requires %s of storage and can't be performed because only %s "
"available."
msgstr ""
"Операция не может быть выполнена, так как для ее выполнения требуется %s в "
"хранилище, однако доступно только %s."

#: storage.py:275
msgid "Estimation is already running"
msgstr "Процесс оценки хранилища уже запущен"

#: test/test_exception.py:75
#, python-format
msgid "The answer is %d"
msgstr "Ответ %d"

